<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Products;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
                Products::create(array('id' => '1','nm_products' => 'L\'OREAL colored shampoo - vitamin color','category_products_id' => '1','quantity' => '77','deskripsi' => 'Shampoo khusus rambut yang rusak akibat pewarna, dengan bantuan khasiat didalamnya membuat rambut kembali sehat. Isi 300 ml','price' => '40000','slug' => 'loreal-colored-shampoo-vitamin-color','image' => 'product-images/pCQWcHFybiy2jRADUSHThJ0RJIi9XN1R2bR0tpC3.jpg','created_at' => '2022-09-13 14:43:24','updated_at' => '2022-10-15 04:17:46'));

            Products::create(array('id' => '2','nm_products' => 'Kerastase Shampoo','category_products_id' => '1','quantity' => '79','deskripsi' => 'Shampoo yang melindungi kulit kepala dari panas Hingga 230 derajat celcius, dan memiliki anti-oksidan yang menjaga warna rambut, mengurangi kusut berlebihan.','price' => '120000','slug' => 'kerastase-shampoo','image' => 'product-images/jURZJV9N6NmX72quVcnrE7egIj9ERMwwA5DPXjf9.jpg','created_at' => '2022-09-13 14:49:13','updated_at' => '2022-09-14 01:47:55'));

            Products::create(array('id' => '3','nm_products' => 'Sunsilk Yellow','category_products_id' => '1','quantity' => '0','deskripsi' => 'Shampo sunsilk 340ml','price' => '35000','slug' => 'sunsilk-yellow','image' => 'product-images/omueVW9xFriN18rwk0wy7pUVBTyMXKABYX4o1tFn.jpg','created_at' => '2022-09-13 14:55:36','updated_at' => '2022-10-14 16:48:51'));

            Products::create(array('id' => '4','nm_products' => 'Clear Triple anti dandruff technology','category_products_id' => '1','quantity' => '42','deskripsi' => 'Shampoo clear dengan triple anti ketombe membantu mengembalikan komponen protein kulit kepala','price' => '39000','slug' => 'clear-triple-anti-dandruff-technology','image' => 'product-images/cGtN6dQ8zjbDcEJD36wmZMd0Aq8CFyUIDsgJunlr.jpg','created_at' => '2022-09-13 14:57:18','updated_at' => '2022-09-14 03:20:31'));

            Products::create(array('id' => '5','nm_products' => 'Head & shoulders','category_products_id' => '1','quantity' => '28','deskripsi' => 'Membantu merawat rambut, membersihkan kulit kepala dari ketombe dan menutrisi rambut hingga ujung rambut.','price' => '35000','slug' => 'head-shoulders','image' => 'product-images/vTywwewkKPLqfPjUv9Aem6TEn0R0k8NbW1pSiF5z.jpg','created_at' => '2022-09-13 15:00:21','updated_at' => '2022-09-13 15:00:21'));

            Products::create(array('id' => '6','nm_products' => 'Natur Shampoo Aloe vera','category_products_id' => '1','quantity' => '33','deskripsi' => 'Shampoo herbal dengan ekstrak aloe vera yang harum dan menyehatkan rambut.','price' => '45000','slug' => 'natur-shampoo-aloe-vera','image' => 'product-images/TaEfktv7FGz8vEzuhyBzVCf74E1gFcLGvXw0baSc.jpg','created_at' => '2022-09-13 15:01:39','updated_at' => '2022-09-26 14:17:14'));

            Products::create(array('id' => '7','nm_products' => 'Pantene perfection Conditioner','category_products_id' => '2','quantity' => '49','deskripsi' => 'Conditioner pantene tanpa bilas. Isi bersih 40ml','price' => '30000','slug' => 'pantene-perfection-conditioner','image' => 'product-images/qlSXT8Z8Es8SQmMgFGWjGJuOREQtTzdmga5E4bSA.jpg','created_at' => '2022-09-13 15:04:55','updated_at' => '2022-09-13 15:04:55'));

            Products::create(array('id' => '8','nm_products' => 'TRESemme Conditioner Keratine smooth','category_products_id' => '2','quantity' => '74','deskripsi' => 'Conditioner Tresemme dengan ekstrak keratine smooth membuat rambut tampak halus dan lurus. Isi bersih 170ml','price' => '45000','slug' => 'tresemme-conditioner-keratine-smooth','image' => 'product-images/TOHZGEGiPVNLRtnpo0MrxJjSEshnol8xg7DenLkp.jpg','created_at' => '2022-09-13 15:06:27','updated_at' => '2022-09-13 15:06:27'));

            Products::create(array('id' => '9','nm_products' => 'Pantene Biotin Strength Conditioner','category_products_id' => '2','quantity' => '24','deskripsi' => 'Pantene biotin strength dengan hair supplement membuat rambut tampak sehat. Isi bersih 150ml','price' => '23000','slug' => 'pantene-biotin-strength-conditioner','image' => 'product-images/Ed6PhyAQP4jvrfAnx4O2lsidugPhX0wxM4ofFKNH.jpg','created_at' => '2022-09-13 15:07:52','updated_at' => '2022-09-13 15:07:52'));

            Products::create(array('id' => '10','nm_products' => 'Natur Conditioner Aloe vera','category_products_id' => '2','quantity' => '15','deskripsi' => 'Natur aloe vera memiliki kandungan aloe vera atau lidah buaya yang membuat rambut sehat karena tidak banyak menggunakan bahan kimia buatan yang dapat merusak rambut.','price' => '30000','slug' => 'natur-conditioner-aloe-vera','image' => 'product-images/Qm2PQY3xf4MoLYmTKPWeXqgDWvKx3kqhSLjAeKaN.jpg','created_at' => '2022-09-13 15:09:22','updated_at' => '2022-09-14 01:47:55'));

            Products::create(array('id' => '11','nm_products' => 'Ms glow men Black Oats Facial wash','category_products_id' => '3','quantity' => '17','deskripsi' => 'Ms glow men jadikan kulit wajah yang cerah dan sehat dengan energizer, Facial wash yang ampuh mengangkat sel kulit mati dan noda','price' => '45000','slug' => 'ms-glow-men-black-oats-facial-wash','image' => 'product-images/e7xAjCY7JUG9NxYvo09GGBuNuMSfmFb4wCSeFaVw.jpg','created_at' => '2022-09-14 00:01:16','updated_at' => '2022-09-14 03:23:28'));

            Products::create(array('id' => '13','nm_products' => 'Kahf Facial wash anti komedo','category_products_id' => '3','quantity' => '26','deskripsi' => 'Kahf facial wash yang menangkal dan mengangkat komedo dalam 7 hari','price' => '34000','slug' => 'kahf-facial-wash-anti-komedo','image' => 'product-images/mdpDhOCUpSiUHWQgRODIDPBCWiLDRDodEn3eLKih.jpg','created_at' => '2022-09-14 00:02:53','updated_at' => '2022-09-14 00:02:53'));

            Products::create(array('id' => '14','nm_products' => 'Nivea men facial foam','category_products_id' => '3','quantity' => '42','deskripsi' => 'Nivea men facial foam dengan extra white 10x effect yang menghilangkan dark spot pada kulit wajah. Isi bersih 50ml','price' => '29000','slug' => 'nivea-men-facial-foam','image' => 'product-images/3FnWzMYFxHNf9M1K9ZHfV3uJeQcejj0ehJIRzQhP.jpg','created_at' => '2022-09-14 00:04:46','updated_at' => '2022-09-14 00:04:46'));

            Products::create(array('id' => '15','nm_products' => 'Pond\'s men white boost','category_products_id' => '3','quantity' => '36','deskripsi' => 'Pond\'s men white boost dengan whitening dan menghilangkan dark spot pada kulit wajah.','price' => '31000','slug' => 'ponds-men-white-boost','image' => 'product-images/ae7DzgF0UgQuXP6ccKYWn5iTISn7kqYlcQyHkGnP.jpg','created_at' => '2022-09-14 00:05:59','updated_at' => '2022-09-14 00:05:59'));

            Products::create(array('id' => '16','nm_products' => 'You treat acne','category_products_id' => '3','quantity' => '12','deskripsi' => 'You treat acne menjaga kulit wajah agar terhindar dari jerawat dalam 40 hari.','price' => '39000','slug' => 'you-treat-acne','image' => 'product-images/Ovt4CHFEROFSD2WFcG9n3M0k0LmqmDjWWikKZr3z.jpg','created_at' => '2022-09-14 00:07:41','updated_at' => '2022-09-14 00:07:41'));

            Products::create(array('id' => '17','nm_products' => 'BIOAQUA','category_products_id' => '3','quantity' => '28','deskripsi' => 'Bioaqua cleanser yang membersihkan dan mencerahkan kulit wajah dengan kandungan 0% alkohol yang dapat merusak kulit wajah.','price' => '60000','slug' => 'bioaqua','image' => 'product-images/Tr1Z5edzXrqlqvzRgxqVJqabnHT4ShMdTI06m1R4.jpg','created_at' => '2022-09-14 00:09:13','updated_at' => '2022-09-14 03:20:31'));

            Products::create(array('id' => '18','nm_products' => 'Pond\'s Brightening Essence','category_products_id' => '4','quantity' => '11','deskripsi' => 'Pond\'s men brightening essence yang mencerahkan dan menjaga kulit wajah. Isi bersih 50ml','price' => '45000','slug' => 'ponds-brightening-essence','image' => 'product-images/IbAkGfhbHOFxdYRrcvbZIkjlzsnNrqFT5HuLP7uH.jpg','created_at' => '2022-09-14 00:12:39','updated_at' => '2022-09-18 12:20:42'));

            Products::create(array('id' => '19','nm_products' => 'Wardah nature daily','category_products_id' => '4','quantity' => '25','deskripsi' => 'Wardah nature daily dengan kandungan hydramic aloe toner essence. Isi bersih 100ml','price' => '45000','slug' => 'wardah-nature-daily','image' => 'product-images/AKNf885Q5vfLj5CANbdZxR8JUrCQ03jSNMEj84eb.jpg','created_at' => '2022-09-14 00:14:14','updated_at' => '2022-09-14 01:47:55'));

            Products::create(array('id' => '20','nm_products' => 'You golden age Essence','category_products_id' => '4','quantity' => '18','deskripsi' => 'You golden age Essence dengan ekstrak bengkoang dan bahan herbal yang menjaga kulit dan mencerahkan wajah. Isi bersih 100ml','price' => '52000','slug' => 'you-golden-age-essence','image' => 'product-images/L2nQXoL89PGMHLzGirAO13yycil5gE6Oaif0NceI.jpg','created_at' => '2022-09-14 00:15:43','updated_at' => '2022-09-14 00:15:43'));

            Products::create(array('id' => '21','nm_products' => 'Scarlett brightly essence','category_products_id' => '4','quantity' => '49','deskripsi' => 'Scarlett brightly essence toner untuk kulit normal dan kering. Isi bersih 100ml','price' => '67000','slug' => 'scarlett-brightly-essence','image' => 'product-images/X52uSPLCOykKsL8zU5BzWG5U1343207lHWii0jKq.jpg','created_at' => '2022-09-14 00:16:50','updated_at' => '2022-09-14 00:16:50'));

            Products::create(array('id' => '22','nm_products' => 'Wardah Essence toner','category_products_id' => '4','quantity' => '43','deskripsi' => 'Wardah essence toner dengan 100% natural aloe vera dan PH balance untuk seimbangkan ph kulit di wajah, menyegarkan, sekaligus melembapkan kulit.','price' => '56000','slug' => 'wardah-essence-toner','image' => 'product-images/16xTPlgaIToCmyXsjVIrLGj76WLI8CVDrE30EDMZ.jpg','created_at' => '2022-09-14 00:18:30','updated_at' => '2022-09-14 00:18:30'));

            Products::create(array('id' => '23','nm_products' => 'Wardah Perfect bright','category_products_id' => '5','quantity' => '19','deskripsi' => 'Wardah perfect bright + oil control menghilangkan lemak dan mencerahkan wajah hingga 24 jam. Isi bersih 20ml','price' => '34000','slug' => 'wardah-perfect-bright','image' => 'product-images/KhHXzlir1FB3TgqXApgW2CAQfDFC9HRI1Kfxk2AS.jpg','created_at' => '2022-09-18 12:25:49','updated_at' => '2022-09-18 12:25:49'));

            Products::create(array('id' => '24','nm_products' => 'Ponds Moisturizer','category_products_id' => '5','quantity' => '123','deskripsi' => 'Ponds moisturizer natural dapat mencerahkan kulit wajah tanpa takut dengan bahan kimia yang berbahaya. Isi bersih 20 gram','price' => '20000','slug' => 'ponds-moisturizer','image' => 'product-images/jxoUb4LTBwY7qnyfFJtGV1s70ioVvUPEp6x5rzaE.jpg','created_at' => '2022-09-18 12:27:10','updated_at' => '2022-09-18 12:27:10'));

            Products::create(array('id' => '25','nm_products' => 'Skintific ceramide moisturizer','category_products_id' => '5','quantity' => '23','deskripsi' => 'Skintific ceramide moisturizer dapat membantu menghidrasi dan melembabkan kulit wajah hingga 5x.','price' => '42000','slug' => 'skintific-ceramide-moisturizer','image' => 'product-images/77USDtPksHrNM3ibcOzeF0AUs686JXJYLFurGVoQ.jpg','created_at' => '2022-09-18 12:28:46','updated_at' => '2022-09-18 12:28:46'));

            Products::create(array('id' => '26','nm_products' => 'Somethinc Moisturizer','category_products_id' => '5','quantity' => '35','deskripsi' => 'Somethinc Moisturizer dengan bahan Niacinamide + Moisture Sabi Beet Serum yang dapat mencerahkan wajah anda seperti Oppa Oppa korea!','price' => '59000','slug' => 'somethinc-moisturizer','image' => 'product-images/dYbA6ZTOKGrweZkvUIjqEzXcbfA9oaQoyoddLGDJ.jpg','created_at' => '2022-09-18 12:30:24','updated_at' => '2022-09-18 12:30:24'));

            Products::create(array('id' => '27','nm_products' => 'Somethinc Serum','category_products_id' => '6','quantity' => '324','deskripsi' => 'Somethinc serum untuk menghidrasi kulit kering akibat sinar matahari, dengan kandungan 9x Hyaluronic + pro vitamin B5, dan belgium Onsen Sui Water yang dapat melembabkan kulit hingga 48jam.','price' => '47000','slug' => 'somethinc-serum','image' => 'product-images/ynyhdPRfg87m67GXZm0h2ZhBfPlumzxXnmFUEPwc.jpg','created_at' => '2022-09-18 12:32:40','updated_at' => '2022-09-18 12:32:40'));

            Products::create(array('id' => '28','nm_products' => 'Scarlet Bifida Serum','category_products_id' => '6','quantity' => '47','deskripsi' => 'Scarlett Bifida Serum dengan kandungan Hyalu B5 + Reishi mushroom & Bifida serum untuk kulit kering dan memiliki tanda tanda penuaan','price' => '370000','slug' => 'scarlet-bifida-serum','image' => 'product-images/hx7wB6CszZjqkJ4VOvxWtpNWGluuWNcerWrA3QQQ.jpg','created_at' => '2022-09-18 12:34:23','updated_at' => '2022-09-18 12:34:23'));

            Products::create(array('id' => '29','nm_products' => 'Somethinc Hyaluronic 9+ Serum','category_products_id' => '6','quantity' => '47','deskripsi' => 'Somethinc serum dapat melembabkan kulit hingga 48 jam dan menjaga elastisitas kulit serta meredakan kemerahan.','price' => '54000','slug' => 'somethinc-hyaluronic-9-serum','image' => 'product-images/4qAmjO9uaJg7ElxWfwWdRUR7x3oRDAgCaR9eXrRc.jpg','created_at' => '2022-09-18 12:41:38','updated_at' => '2022-09-18 13:10:48'));

            Products::create(array('id' => '30','nm_products' => 'Lavojoy TRI OIL body serum','category_products_id' => '6','quantity' => '16','deskripsi' => 'Lavojoy TRI OIL Serum dapat mencerahkan dan melembabkan kulit','price' => '29000','slug' => 'lavojoy-tri-oil-body-serum','image' => 'product-images/nJ92EhvgqYQBKBelPOeub83igJIHfO08BqWxuOOI.jpg','created_at' => '2022-09-18 12:43:11','updated_at' => '2022-09-18 12:43:11'));

            Products::create(array('id' => '31','nm_products' => 'Wardah Lightening serum','category_products_id' => '6','quantity' => '42','deskripsi' => 'Wardah lightening serum 10x lebih kuat mencerahkan wajah. Isi bersih 8 ml','price' => '42000','slug' => 'wardah-lightening-serum','image' => 'product-images/JsXmP7I3QMT835TUyuJWLJP7EVzu9ZnntKdqfVRB.jpg','created_at' => '2022-09-18 12:44:27','updated_at' => '2022-09-18 12:44:27'));

            Products::create(array('id' => '32','nm_products' => 'You Triple UV Sunscreen','category_products_id' => '7','quantity' => '49','deskripsi' => 'Your triple UV Suncscreen suitable untuk kulit berminyak. Isi bersih 30 ml dengan kandungan SPF 50+','price' => '70000','slug' => 'you-triple-uv-sunscreen','image' => 'product-images/X5WGQETxgmRRnYnr8pr6CwUcOrPUGd4XQUdp1JqF.jpg','created_at' => '2022-09-18 13:11:18','updated_at' => '2022-09-18 13:11:18'));

            Products::create(array('id' => '33','nm_products' => 'Wardah UV Shield Essential Sunscreen Gel 40ml','category_products_id' => '7','quantity' => '89','deskripsi' => 'Wardah UV Shield Essential Sunscreen Gel MERUPAKAN #1 UV shield sunscreen di indonesia dengan kandungan 0% alkohol dan SPF 30+ mampu melindungi kulit dari sinar matahari.','price' => '43000','slug' => 'wardah-uv-shield-essential-sunscreen-gel-40ml','image' => 'product-images/FawnAyVKmaDZ7HLfQcbxlpVbRqJ0xaD9z1ORK3wo.jpg','created_at' => '2022-09-18 13:13:14','updated_at' => '2022-09-18 13:13:14'));

            Products::create(array('id' => '34','nm_products' => 'Joylab aqua Sunscreen','category_products_id' => '7','quantity' => '37','deskripsi' => 'Joylab aqua Sunscreen dengan formula SPF 50+ yang dapat melindungi kulit mu dari sinar matahari dengan perlindungan tahan lama!','price' => '49000','slug' => 'joylab-aqua-sunscreen','image' => 'product-images/lIbV4z2xIMbNGJ5C4SE97D2qJwf1isc8DIBFFYYk.jpg','created_at' => '2022-09-18 13:16:21','updated_at' => '2022-09-18 13:16:21'));

            Products::create(array('id' => '35','nm_products' => 'Hanasui Collagen Sunscreen','category_products_id' => '7','quantity' => '41','deskripsi' => 'Hanasui Collagen Sunscreen dengan kandungan collagen Water 3x lebih baik memberikan kelembapan pada kulit dan dengan SPF 50+ yang melindungi kulit hingga 90% dari sinar UV.','price' => '47000','slug' => 'hanasui-collagen-sunscreen','image' => 'product-images/miitjOLlSvIKO4Mkr7x5fBSMSgbQEBkShCvxcAvA.jpg','created_at' => '2022-09-19 01:54:59','updated_at' => '2022-09-19 01:54:59'));

            Products::create(array('id' => '36','nm_products' => 'Luminous White Glow Sunscreen','category_products_id' => '7','quantity' => '52','deskripsi' => 'Luminous White Glow Sunscreen dengan kandungan Natural Whitening centella. Wajah cerah dan tidak jerawatan.','price' => '500000','slug' => 'luminous-white-glow-sunscreen','image' => 'product-images/P8P3NmvOyANHY6f7q51gQbqaCu0puhP0PUHbg9TT.jpg','created_at' => '2022-09-19 01:58:27','updated_at' => '2022-09-19 01:58:27'));

            Products::create(array('id' => '37','nm_products' => 'Emina Sun Protection','category_products_id' => '7','quantity' => '52','deskripsi' => 'Emina Sun Protection dengan kandungan SPF 30 yang menjaga kulit dari sinar UV, mengandung aloe vera ekstrak yang alami dapat mencerahkan kulit wajah.','price' => '49000','slug' => 'emina-sun-protection','image' => 'product-images/nLovCUpS6Y8emRpZiALv8veI0CWayICqIN3zFOpk.jpg','created_at' => '2022-09-19 02:03:20','updated_at' => '2022-09-19 02:03:20'));

            Products::create(array('id' => '38','nm_products' => 'Gatsby Powder Clay','category_products_id' => '8','quantity' => '45','deskripsi' => 'Gatsby Powder Clay produk hair styling rambut agar dapat mengembang 24 jam. Isi bersih 20gram','price' => '60000','slug' => 'gatsby-powder-clay','image' => 'product-images/KU4BK5FEGFzbLlFa7lE1DxGAHRGnpKERXbVKBFRY.jpg','created_at' => '2022-09-19 02:10:02','updated_at' => '2022-09-19 02:10:02'));

            Products::create(array('id' => '39','nm_products' => 'Masbrews Volume Powder','category_products_id' => '8','quantity' => '54','deskripsi' => 'Masbrews volume powder untuk gaya rambut pria agar bergelombang dan gampang di atur','price' => '54000','slug' => 'masbrews-volume-powder','image' => 'product-images/JXf8MaTdU0yB7OKQZdf11INS4cXxV63arqtv7D9H.jpg','created_at' => '2022-09-19 02:12:19','updated_at' => '2022-09-19 02:12:19'));

            Products::create(array('id' => '40','nm_products' => 'YUU men Gold Royale Vanilla Hair Powder','category_products_id' => '8','quantity' => '45','deskripsi' => 'Gold Royale Vanilla Hair Powder memberikan tekstur rambut yang ngembang dan halus, dengan aroma vanilla yang dapat bertahan hingga 24 jam.','price' => '19000','slug' => 'yuu-men-gold-royale-vanilla-hair-powder','image' => 'product-images/f4sojEJKZxzDuZvwiZgLIS1JFhjylmOBMd9eKrk7.jpg','created_at' => '2022-09-19 02:17:08','updated_at' => '2022-09-19 02:17:08'));

            Products::create(array('id' => '41','nm_products' => 'YUU men Blue Royale Bubble Gum Hair Powder','category_products_id' => '8','quantity' => '43','deskripsi' => 'Blue Royale Bubble Gum hair powder memberikan tekstur rambut yang ngembang dan halus, dengan aroma Permen karet yang dapat bertahan hingga 24 jam.','price' => '54000','slug' => 'yuu-men-blue-royale-bubble-gum-hair-powder','image' => 'product-images/fBRB6orNS7R5p6gCvcmURIxHPiABTGhdLloS57gR.jpg','created_at' => '2022-09-19 02:19:43','updated_at' => '2022-09-19 02:19:43'));

            Products::create(array('id' => '42','nm_products' => 'Gatsby Water Gloss Pomade','category_products_id' => '8','quantity' => '12','deskripsi' => 'Gatsby Water Gloss Hypersolid dapat membuat rambut glossy dan mudah diatur. Isi bersih 300gram','price' => '34000','slug' => 'gatsby-water-gloss-pomade','image' => 'product-images/wVI92goa1TMy5mYgxuvlMRn0c7Yh73ZvsLJR33sG.jpg','created_at' => '2022-09-19 02:21:48','updated_at' => '2022-09-19 02:21:48'));

            Products::create(array('id' => '43','nm_products' => 'Gatsby Styling Pomade','category_products_id' => '8','quantity' => '12','deskripsi' => 'Gatsby Pomade Perfect Rise dapat menambah gaya rambut menjadi glossy dan mudah di atur.','price' => '30000','slug' => 'gatsby-styling-pomade','image' => 'product-images/0kmMkaBtHhSgXYBqyHQtI3iMI5qZiQ9uzDoUkQQY.jpg','created_at' => '2022-09-19 02:23:15','updated_at' => '2022-09-19 02:23:15'));

            Products::create(array('id' => '44','nm_products' => 'Lavojoy Amino Acid Body Wash','category_products_id' => '9','quantity' => '26','deskripsi' => 'Lavojoy Amino Acid Body Wash dengan kandungan polished dan radiant gently cleanse.','price' => '12000','slug' => 'lavojoy-amino-acid-body-wash','image' => 'product-images/ARJn14DDQkmbUVLxQ2DZ9Bmj3FjwzHNDVYEEfgH0.jpg','created_at' => '2022-09-19 02:25:51','updated_at' => '2022-09-19 02:25:51'));

            Products::create(array('id' => '45','nm_products' => 'Cloris Men Body wash','category_products_id' => '9','quantity' => '41','deskripsi' => 'Cloris Men Body wash dengan kandungan charcoal powder dan coconut oil yang ramah untuk kulit dan dapat mencerahkan hingga 24 jam.','price' => '30000','slug' => 'cloris-men-body-wash','image' => 'product-images/FCRxYXqDBi1Wo5vd2KPTVUifXAEiP8OxbL7SGDHI.jpg','created_at' => '2022-09-19 02:29:37','updated_at' => '2022-09-19 02:29:37'));

            Products::create(array('id' => '46','nm_products' => 'GIV Glowing white Bodywash','category_products_id' => '9','quantity' => '59','deskripsi' => 'GIV glowing white sabun mandi cair dengan kandungan mulberry dan collagen.','price' => '15000','slug' => 'giv-glowing-white-bodywash','image' => 'product-images/5psckiObcHX6BhSsaywMYUowR3Q01n8T98l6SN5b.jpg','created_at' => '2022-09-19 02:31:50','updated_at' => '2022-09-19 02:31:50'));

            Products::create(array('id' => '47','nm_products' => 'Pepsodent Silver Charcoal Toothbrust','category_products_id' => '10','quantity' => '120','deskripsi' => 'Pepsodent Silver Charcoal Toothbrust dengan kandungan silver charcoal yang dapat membersihkan karang gigi','price' => '10000','slug' => 'pepsodent-silver-charcoal-toothbrust','image' => 'product-images/F4cDkLMwq22SjQLwR2987VwTN8igb0cYEVhxMWTU.jpg','created_at' => '2022-09-19 02:40:36','updated_at' => '2022-09-19 02:40:36'));

            Products::create(array('id' => '48','nm_products' => 'Oral-B Cross Action Ultrathin','category_products_id' => '10','quantity' => '19','deskripsi' => 'Sikat gigi Oral-B Cross Action Ultrathin dengan kandungan ultrathin charcoal dengan extra soft dan deep clean.','price' => '15000','slug' => 'oral-b-cross-action-ultrathin','image' => 'product-images/KRSXjA14f7APhE9ePMo2FWIzkg0MkjTaIZvxgzT0.jpg','created_at' => '2022-09-19 02:43:16','updated_at' => '2022-09-19 02:43:16'));

            Products::create(array('id' => '49','nm_products' => 'Jo Malone Belgian Chocolate','category_products_id' => '11','quantity' => '20','deskripsi' => 'Parfume Jo Malone Belgian Chocolate dengan wangy Eau de cologne yang berasal dari London.','price' => '80000','slug' => 'jo-malone-belgian-chocolate','image' => 'product-images/zDO427Wndrpo8n2sas1a1koYp2UWXgbsjHPcTAwV.jpg','created_at' => '2022-09-19 02:48:40','updated_at' => '2022-09-19 02:48:40'));

            Products::create(array('id' => '52','nm_products' => 'De\'Xandra nemesis Parfume','category_products_id' => '11','quantity' => '29','deskripsi' => 'De\'Xandra nemesis dengan wangi yang memberikan kesan ramah,cocok untuk sehari-hari seperti untuk bekerja atau meeting.  dengan kandungan Lychee,Orange dan Tonka Bean','price' => '35000','slug' => 'dexandra-nemesis-parfume','image' => 'product-images/wxamJKHYNUYrlAV2XEXElPKJyehp9dy07BtQh9l1.jpg','created_at' => '2022-09-19 03:22:43','updated_at' => '2022-09-19 03:22:43'));

            Products::create(array('id' => '53','nm_products' => 'Evangeline Black Vanilla','category_products_id' => '11','quantity' => '49','deskripsi' => 'Parfume Evangeline bkacl vanilla dengan wangy semerback bunga dengan ciri khas black vanilla yang dapat dipakai di dalam ruangan dengan wangi mencapai 24 jam','price' => '61000','slug' => 'evangeline-black-vanilla','image' => 'product-images/3G4XvOMnH63k750NTiGbNIksDtG5yDXre2NwMu0O.jpg','created_at' => '2022-09-19 03:25:13','updated_at' => '2022-09-19 03:25:13'));

            Products::create(array('id' => '54','nm_products' => 'Black opium','category_products_id' => '11','quantity' => '8','deskripsi' => 'Black opium premium Yves Saint Laurent parfume import dari benua eropa dengan wangy yang premium.','price' => '100000','slug' => 'black-opium','image' => 'product-images/t2FZMhMAyvAjjyQQqanXVFJToiN10ju2rDlhbww4.jpg','created_at' => '2022-09-19 03:27:19','updated_at' => '2022-09-19 03:27:19'));

            Products::create(array('id' => '55','nm_products' => 'Blaise Dream Catcher','category_products_id' => '11','quantity' => '23','deskripsi' => 'Parfume Blaise Dream Catcher dengan wangy soft dan sweet yang cocok dipakai untuk anak muda yang mau tampil dengan wangy yang fresh.','price' => '39000','slug' => 'blaise-dream-catcher','image' => 'product-images/2Ql1zWEyiqL4wISygl77oVsWsQRfpE9xWtjK1nrw.jpg','created_at' => '2022-09-19 03:28:52','updated_at' => '2022-09-19 03:28:52'));

            Products::create(array('id' => '56','nm_products' => 'JoyRose Grey natural spray','category_products_id' => '11','quantity' => '39','deskripsi' => 'JoyRose Grey parfume natural spray dengan wangy Vaporasite\'ur yang diimport dari benua eropa.','price' => '40000','slug' => 'joyrose-grey-natural-spray','image' => 'product-images/A7xRNS2hsQ0Qbmc8g04jtSvJNIQdURTj1WCvnrD8.jpg','created_at' => '2022-09-19 03:29:59','updated_at' => '2022-09-19 03:29:59'));

            Products::create(array('id' => '58','nm_products' => 'Lavojoy Tri-Oil Body Lotion','category_products_id' => '12','quantity' => '29','deskripsi' => 'Lavojoy Tri-Oil Body Serum dapat mencerahkan, memoisturizing dan menjaga kulit kita','price' => '39000','slug' => 'lavojoy-tri-oil-body-lotion','image' => 'product-images/tiVzxiru9Bx8nDYbQ7EkSuPJMdNxINnIguuZ1yH3.jpg','created_at' => '2022-09-19 03:34:43','updated_at' => '2022-09-19 03:34:43'));

            Products::create(array('id' => '59','nm_products' => 'Marina Healthy & Glow','category_products_id' => '12','quantity' => '39','deskripsi' => 'Marina Healthy & Glow dapat membuat kulit tampil lebih cerah merata dan sehat bercahaya  dengan kandungan 3x active white.','price' => '15000','slug' => 'marina-healthy-glow','image' => 'product-images/rgKniGzA8Hh2vARFc16WHIxCZapleVgU8P7IVTXl.jpg','created_at' => '2022-09-19 03:37:00','updated_at' => '2022-09-19 03:37:00'));

            Products::create(array('id' => '60','nm_products' => 'Marina Nourished & Healthy','category_products_id' => '12','quantity' => '28','deskripsi' => 'Marina Nourished & Healthy dapat menutrisi kulit sehat mu dan memoisturizing , melembabkan kulit hingga 24 jam dengan kandungan bengkoang murni.','price' => '15000','slug' => 'marina-nourished-healthy','image' => 'product-images/uSOLWIoQV4twsfX4xTFg5olPGqBL4hVvKcpoUEsM.jpg','created_at' => '2022-09-19 03:38:20','updated_at' => '2022-09-19 03:38:20'));

            Products::create(array('id' => '61','nm_products' => 'Marina Protects and Cares','category_products_id' => '12','quantity' => '23','deskripsi' => 'Marina Protects and Cares dapat melindungi kulit saat beraktivitas di luar ruangan dengan kandungan Ekstrak Apple dan grapefruit yang dapat memoisturizing kulit hingga 24 jam','price' => '15000','slug' => 'marina-protects-and-cares','image' => 'product-images/QtabRhOdFltqDiUBdrKewqPFFmnVoPcEkVuySxUu.jpg','created_at' => '2022-09-19 03:39:54','updated_at' => '2022-09-19 03:39:54'));

            Products::create(array('id' => '62','nm_products' => 'Swana Brightening body lotion','category_products_id' => '12','quantity' => '33','deskripsi' => 'Swana Brightening body lotion dengan perpaduan vitamin C dan niacinamide yang dapat mencerahkan kulit dan mengandung ekstrak peach yang kaya akan vitamin dan pelembab yang baik.','price' => '20000','slug' => 'swana-brightening-body-lotion','image' => 'product-images/Je9gt2DIwwJc7tyuf9Hz5CRZR1dwFGuTFYzfIwCB.jpg','created_at' => '2022-09-19 03:41:52','updated_at' => '2022-09-19 03:41:52'));

            Products::create(array('id' => '63','nm_products' => 'Love beauty and planet Body lotion','category_products_id' => '12','quantity' => '29','deskripsi' => 'Love beauty and planet Body lotion with Argan oil & lavender aroma soothe and serene untuk kulit yang kering dan membutuhkan banyak nutrisi','price' => '40000','slug' => 'love-beauty-and-planet-body-lotion','image' => 'product-images/hJeCOZ5BgRaYwoj0sHFEPnRXqGYxCjBioS1JmTPt.jpg','created_at' => '2022-09-19 03:43:47','updated_at' => '2022-09-19 03:43:47'));

            Products::create(array('id' => '64','nm_products' => 'Versident Shinning Bright Teeth','category_products_id' => '13','quantity' => '12','deskripsi' => 'Versident Shinning Bright Teeth pasta gigi perontok karang dan pemutih gigi yang baik dengan bahan alami.','price' => '23000','slug' => 'versident-shinning-bright-teeth','image' => 'product-images/6JHnyuMTAYn3oTRaTDcRJn6b1pVg64MpjoS8gGDO.jpg','created_at' => '2022-09-19 03:45:13','updated_at' => '2022-09-19 03:45:13'));

            Products::create(array('id' => '65','nm_products' => 'Closeup Everfresh','category_products_id' => '13','quantity' => '70','deskripsi' => 'Pasta gigi Closeup Everfresh dengan formula triple fresh dan anti bacterial yang dapat menjaga mulut agar tetap segar dan terhindar dari kuman','price' => '10000','slug' => 'closeup-everfresh','image' => 'product-images/3BdVoxb5JLEBqxAddf9wP0677z45SpHGyHTXyOqR.jpg','created_at' => '2022-09-19 03:46:44','updated_at' => '2022-09-19 03:46:44'));

            Products::create(array('id' => '66','nm_products' => 'Makarizo Hair energy','category_products_id' => '14','quantity' => '49','deskripsi' => 'Makarizo hair energy fibertherapy conditioning shampoo dengan ekstrak kiwi yang dapat merawat rambut berwarna dan dari proses kimia.','price' => '30000','slug' => 'makarizo-hair-energy','image' => 'product-images/DYhfFQj59QeoaVKMrB3QYbyCJSsbodgbQviAhLui.jpg','created_at' => '2022-09-19 03:48:58','updated_at' => '2022-09-19 03:48:58'));

            Products::create(array('id' => '68','nm_products' => 'Makarizo Hair Energy Scentsation','category_products_id' => '14','quantity' => '239','deskripsi' => 'Makarizo Hair Energy dengan kandungan UV protection dan scentech-f yang dapat melindungi rambut dari kerusakan akibat sinar UV','price' => '28000','slug' => 'makarizo-hair-energy-scentsation','image' => 'product-images/8tvLXx47RQ4FQGxLIZuL26BQVAtxtEnwYs61TwCv.jpg','created_at' => '2022-09-19 03:50:32','updated_at' => '2022-09-19 03:50:32'));

            Products::create(array('id' => '69','nm_products' => 'Advisor hair recovery','category_products_id' => '14','quantity' => '30','deskripsi' => 'Advisor hair recovery   dengan kandungan multi vitamin treatment yang membuat rambut sehat dan kuat','price' => '40000','slug' => 'advisor-hair-recovery','image' => 'product-images/piC65FOzlsdNlpjPpnEdrrYrfzV0dqsFwuPelYdc.jpg','created_at' => '2022-09-19 03:51:33','updated_at' => '2022-09-19 03:51:33'));

            Products::create(array('id' => '70','nm_products' => 'Nature hair vitamin olive oil','category_products_id' => '14','quantity' => '10','deskripsi' => 'Natur Hair vitamin dengan kandungan olive oil dan vitamin E untuk rambut yang diwarnai atau rambut yang terpapar proses kimia.','price' => '34000','slug' => 'nature-hair-vitamin-olive-oil','image' => 'product-images/jFDqULwPZvMmS0AHq57Pter6I9XMjQNIS2rFdoDz.jpg','created_at' => '2022-09-19 03:53:05','updated_at' => '2022-09-26 14:17:14')
          );
            Products::create(array('id' => '71','nm_products' => 'Natur haire vitamin olive oil','category_products_id' => '14','quantity' => '20','deskripsi' => 'Natur Hair vitamin dengan kandungan olive oil dan vitamin E untuk rambut yang diwarnai atau rambut yang terpapar proses kimia.','price' => '34000','slug' => 'natur-haire-vitamin-olive-oil','image' => 'product-images/jFDqULwPZvMmS0AHq57Pter6I9XMjQNIS2rFdoDz.jpg','created_at' => '2022-09-19 03:53:05','updated_at' => '2022-09-26 14:17:14')
          );
            Products::create(array('id' => '72','nm_products' => 'Natur hair vitamin olive oil','category_products_id' => '14','quantity' => '0','deskripsi' => 'Natur Hair vitamin dengan kandungan olive oil dan vitamin E untuk rambut yang diwarnai atau rambut yang terpapar proses kimia.','price' => '34000','slug' => 'natur-hair-vitamin-olive-oil','image' => 'product-images/jFDqULwPZvMmS0AHq57Pter6I9XMjQNIS2rFdoDz.jpg','created_at' => '2022-09-19 03:53:05','updated_at' => '2022-09-26 14:17:14')
          );
    }
}
